controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

produit_index:
    path: /produit
    controller: App\Controller\ProduitController::index
